/**
 * Synthetic insurance data used only for the credential-free product demo.
 * Every customer, insurer, product, policy document, and finding below is fictional.
 */
export const INSURANCE_DEMO_CUSTOMER = {
  name: "김가온",
  label: "합성 샘플 고객",
} as const

export const INSURANCE_DEMO_DATA = {
  demoMeta: {
    synthetic: true,
    generatedFor: "KFin Insurance UI demo",
  },
  result: {
    resContractList: [
      {
        resContractNo: "SAMPLE-001",
        resInsuranceName: "가온 암·뇌혈관·심장 종합보험 (시연용)",
        resCompanyName: "가온손해보험 (가상)",
        resContractStatus: "정상",
        resMonthlyPremium: 89400,
        resContractStartDate: "20240115",
        resContractEndDate: "20440115",
        resPaymentCycle: "월납",
        resPaymentPeriod: "20년납",
        resPaidCount: 30,
        resTotalPaymentCount: 240,
        resCoverageList: [
          { resCoverageName: "일반암 진단비", resCoverageAmount: 30000000, source: "codef", confidence: 96, reviewStatus: "confirmed" },
          { resCoverageName: "소액암 진단비", resCoverageAmount: 5000000, source: "codef", confidence: 94, reviewStatus: "confirmed" },
          { resCoverageName: "뇌혈관질환 진단비", resCoverageAmount: 20000000, source: "codef", confidence: 91, reviewStatus: "reviewed" },
          { resCoverageName: "허혈성심장질환 진단비", resCoverageAmount: 20000000, source: "codef", confidence: 90, reviewStatus: "reviewed" },
          { resCoverageName: "항암약물치료비", resCoverageAmount: null, source: "codef", confidence: 86, reviewStatus: "missing" },
        ],
      },
      {
        resContractNo: "SAMPLE-002",
        resInsuranceName: "누리 온가족 암진단 정기보험 (시연용)",
        resCompanyName: "누리생명 (가상)",
        resContractStatus: "정상",
        resMonthlyPremium: 52300,
        resContractStartDate: "20210821",
        resContractEndDate: "20410821",
        resPaymentCycle: "월납",
        resPaymentPeriod: "20년납",
        resPaidCount: 58,
        resTotalPaymentCount: 240,
      },
      {
        resContractNo: "SAMPLE-003",
        resInsuranceName: "다온 실손의료비 보장보험 (시연용)",
        resCompanyName: "다온화재 (가상)",
        resContractStatus: "정상",
        resMonthlyPremium: 31200,
        resContractStartDate: "20230303",
        resContractEndDate: "20330303",
        resPaymentCycle: "월납",
        resPaymentPeriod: "1년 갱신",
        resPaidCount: 40,
        resTotalPaymentCount: 120,
        resCoverageList: [
          { resCoverageName: "질병·상해 실손의료비", resCoverageAmount: null, source: "codef", confidence: 95, reviewStatus: "needs_review" },
        ],
      },
      {
        resContractNo: "SAMPLE-004",
        resInsuranceName: "새봄 치매·간병 생활보험 (시연용)",
        resCompanyName: "새봄생명 (가상)",
        resContractStatus: "정상",
        resMonthlyPremium: 64800,
        resContractStartDate: "20201016",
        resContractEndDate: "20501016",
        resPaymentCycle: "월납",
        resPaymentPeriod: "20년납",
        resPaidCount: 69,
        resTotalPaymentCount: 240,
        resCoverageList: [
          { resCoverageName: "중증치매 진단생활자금", resCoverageAmount: 30000000, source: "certificate", confidence: 99, reviewStatus: "confirmed" },
          { resCoverageName: "간병인 사용입원일당", resCoverageAmount: 100000, source: "certificate", confidence: 99, reviewStatus: "confirmed" },
        ],
      },
      {
        resContractNo: "SAMPLE-005",
        resInsuranceName: "모아 운전자 법률·배상책임 플랜 (시연용)",
        resCompanyName: "모아손해보험 (가상)",
        resContractStatus: "정상",
        resMonthlyPremium: 22900,
        resContractStartDate: "20250211",
        resContractEndDate: "20450211",
        resPaymentCycle: "월납",
        resPaymentPeriod: "20년납",
        resPaidCount: 17,
        resTotalPaymentCount: 240,
        resCoverageList: [
          { resCoverageName: "교통사고처리지원금", resCoverageAmount: 200000000, source: "certificate", confidence: 98, reviewStatus: "confirmed" },
          { resCoverageName: "자동차사고 변호사선임비용", resCoverageAmount: 50000000, source: "certificate", confidence: 98, reviewStatus: "confirmed" },
        ],
      },
      {
        resContractNo: "SAMPLE-006",
        resInsuranceName: "나래 평생안심 종신보험 (시연용)",
        resCompanyName: "나래생명 (가상)",
        resContractStatus: "해지",
        resMonthlyPremium: 121000,
        resContractStartDate: "20160701",
        resContractEndDate: "20660701",
        resPaymentCycle: "월납",
        resPaymentPeriod: "20년납",
        resPaidCount: 62,
        resTotalPaymentCount: 240,
      },
      {
        resContractNo: "SAMPLE-007",
        resInsuranceName: "해솔 골절·화상 수술보험 (시연용)",
        resCompanyName: "해솔화재 (가상)",
        resContractStatus: "정상",
        resMonthlyPremium: 19700,
        resContractStartDate: "20221104",
        resContractEndDate: "20421104",
        resPaymentCycle: "월납",
        resPaymentPeriod: "20년납",
        resPaidCount: 44,
        resTotalPaymentCount: 240,
        resCoverageList: [
          { resCoverageName: "골절 진단비", resCoverageAmount: 300000, source: "codef", confidence: 92, reviewStatus: "needs_review" },
          { resCoverageName: "화상 수술비", resCoverageAmount: 1000000, source: "codef", confidence: 89, reviewStatus: "needs_review" },
        ],
      },
    ],
  },
  insuranceDashboardEnrichment: {
    documents: [
      {
        id: "SAMPLE-DOC-001",
        contractId: "",
        type: "codef",
        name: "CODEF 보험계약 조회 응답",
        status: "connected",
        source: "codef",
        note: "계약 7건 수집 완료 · 일부 담보 가입금액 미제공",
      },
      {
        id: "SAMPLE-DOC-002",
        contractId: "SAMPLE-001",
        type: "certificate",
        name: "가온 종합보험 보험증권 (가상 샘플)",
        status: "connected",
        source: "certificate",
        note: "주요 진단비 가입금액 확인",
      },
      {
        id: "SAMPLE-DOC-003",
        contractId: "SAMPLE-001",
        type: "terms",
        name: "가온 종합보험 암진단 특별약관 (가상 샘플)",
        status: "connected",
        source: "terms",
        note: "문서 버전 및 원문 페이지 연결 완료",
      },
      {
        id: "SAMPLE-DOC-004",
        contractId: "SAMPLE-003",
        type: "certificate",
        name: "다온 실손의료비 보험증권",
        status: "missing",
        source: "unknown",
        note: "가입금액 및 자기부담 구조 확인 필요",
      },
    ],
    decisionScenarios: [
      {
        id: "SAMPLE-SCENARIO-001",
        question: "일반 갑상선암이면 어떤 보장을 검토하나요?",
        diagnosis: "일반 갑상선암",
        treatment: "진단",
        resultStatus: "needs_review",
        summary: "소액암 계열 진단비의 지급 검토 대상입니다. 일반암 납입면제 포함 여부는 연결된 정식 약관에서 별도 확인해야 합니다.",
        candidateAmount: 5000000,
        checks: ["최초 1회 지급 여부", "가입 당시 질병분류표", "일반암 납입면제 제외 여부", "증권상 실제 가입금액"],
        sourceFindingIds: ["SAMPLE-FINDING-001"],
      },
      {
        id: "SAMPLE-SCENARIO-002",
        question: "갑상선암으로 항암약물치료를 받으면 어떻게 되나요?",
        diagnosis: "갑상선암",
        treatment: "항암약물치료",
        resultStatus: "candidate",
        summary: "항암약물치료 담보가 확인되지만 가입금액이 수집되지 않았습니다. 종합병원 여부, 직접 치료 목적, 연간 횟수를 확인한 뒤 지급 후보를 계산합니다.",
        candidateAmount: null,
        checks: ["약관상 항암약물치료 정의", "직접적인 치료 목적", "의료기관 요건", "1일 및 연간 지급한도", "담보 가입금액"],
        sourceFindingIds: ["SAMPLE-FINDING-001"],
      },
      {
        id: "SAMPLE-SCENARIO-003",
        question: "암 진단 후 새 보험으로 바꿔도 되나요?",
        diagnosis: "암 진단 전 계약변경",
        treatment: "승환 검토",
        resultStatus: "needs_review",
        summary: "신규 계약의 90일 암 보장개시와 초기 감액기간 때문에 기존 보장을 먼저 해지하면 공백이 생길 수 있습니다.",
        candidateAmount: null,
        checks: ["신규 계약 승인일", "암 보장개시일", "초기 감액기간", "기존 계약 해지일", "고지 및 인수 결과"],
        sourceFindingIds: ["SAMPLE-FINDING-001"],
      },
    ],
    proposals: [
      {
        id: "SAMPLE-PROPOSAL-001",
        insurer: "새길생명 (가상)",
        productName: "새길 비갱신 암보장 플랜 (시연용)",
        monthlyPremium: 43800,
        planType: "비갱신형 · 20년납 · 무해약환급금형",
        source: "proposal",
        coverages: [
          { categoryId: "cancer", label: "일반암 진단비", amount: 30000000 },
          { categoryId: "cancer", label: "소액암 진단비", amount: 5000000 },
          { categoryId: "treatment", label: "항암약물치료비", amount: 10000000 },
        ],
      },
    ],
    policyFindings: [
      {
        id: "SAMPLE-FINDING-001",
        contractId: "SAMPLE-001",
        coverage: "일반암 진단비",
        matchConfidence: 96,
        paymentTrigger: "암 보장개시일 이후 일반암으로 진단 확정된 경우",
        waitingPeriod: "계약일로부터 90일",
        reductionPeriod: "보장개시일 후 1년 이내 가입금액의 50%",
        paymentFrequency: "최초 1회",
        sourceDocument: "가온 종합보험 암진단 특별약관 (가상 샘플)",
        sourcePage: 43,
      },
      {
        id: "SAMPLE-FINDING-002",
        contractId: "SAMPLE-001",
        coverage: "뇌혈관질환 진단비",
        matchConfidence: 91,
        paymentTrigger: "약관상 뇌혈관질환 분류표에 해당하는 질병으로 진단 확정된 경우",
        waitingPeriod: "별도 면책기간 없음 (가상 샘플 기준)",
        reductionPeriod: "계약 후 1년 이내 가입금액의 50%",
        paymentFrequency: "최초 1회",
        sourceDocument: "가온 종합보험 뇌혈관질환 특별약관 (가상 샘플)",
        sourcePage: 58,
      },
      {
        id: "SAMPLE-FINDING-003",
        contractId: "SAMPLE-003",
        coverage: "질병·상해 실손의료비",
        matchConfidence: 88,
        paymentTrigger: "보장대상 의료비에서 약관상 자기부담금을 차감한 금액",
        waitingPeriod: "별도 면책기간 없음 (가상 샘플 기준)",
        reductionPeriod: "해당 없음",
        paymentFrequency: "연간 한도 내 반복 지급",
        sourceDocument: "다온 실손의료비 보장 특별약관 (가상 샘플)",
        sourcePage: 21,
      },
      {
        id: "SAMPLE-FINDING-004",
        contractId: "SAMPLE-004",
        coverage: "중증치매 진단생활자금",
        matchConfidence: 94,
        paymentTrigger: "약관의 중증치매 상태 정의를 충족하고 진단이 확정된 경우",
        waitingPeriod: "계약일로부터 1년",
        reductionPeriod: "해당 없음",
        paymentFrequency: "진단 확정 후 약정 기간 월 지급",
        sourceDocument: "새봄 치매·간병 생활보험 특별약관 (가상 샘플)",
        sourcePage: 67,
      },
    ],
    changeRisks: [
      {
        id: "SAMPLE-RISK-001",
        contractIds: ["SAMPLE-001", "SAMPLE-002"],
        severity: "high",
        title: "새 계약으로 바꾸면 암 면책기간이 다시 시작될 수 있습니다",
        description: "기존 암 담보를 먼저 해지하면 신규 계약의 보장개시 전 공백이 생길 수 있는 시연 사례입니다.",
        reviewAction: "기존 계약 해지 전에 신규 계약의 승인일과 암 보장개시일을 함께 확인하세요.",
        sourceDocument: "가온 종합보험 암진단 특별약관 (가상 샘플)",
        sourcePage: 43,
      },
      {
        id: "SAMPLE-RISK-002",
        contractIds: ["SAMPLE-003"],
        severity: "high",
        title: "실손 변경 시 자기부담 구조와 갱신 조건이 달라질 수 있습니다",
        description: "보험료만 비교하면 기존 계약의 자기부담률과 보장 제외 항목 차이를 놓칠 수 있습니다.",
        reviewAction: "기존·신규 약관의 자기부담률, 비급여 한도, 갱신 주기를 항목별로 대조하세요.",
        sourceDocument: "다온 실손의료비 보장 특별약관 (가상 샘플)",
        sourcePage: 21,
      },
      {
        id: "SAMPLE-RISK-003",
        contractIds: ["SAMPLE-004"],
        severity: "medium",
        title: "치매 진단 기준과 생활자금 지급 방식 재확인이 필요합니다",
        description: "상품명이 비슷해도 진단 척도와 월 지급 기간이 다를 수 있는 시연 사례입니다.",
        reviewAction: "신규 설계안의 치매 상태 정의와 지급 종료 조건을 기존 약관과 비교하세요.",
        sourceDocument: "새봄 치매·간병 생활보험 특별약관 (가상 샘플)",
        sourcePage: 67,
      },
    ],
  },
} as const
